name: CI

on: [push, pull_request]


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt install texlive-latex-recommended texlive-latex-extra texlive-science
        wget https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-1-amd64.deb && sudo dpkg -i pandoc-2.11.4-1-amd64.deb && rm -f pandoc-2.11.4-1-amd64.deb

    - name: Render Paper
      run: make

    - name: Save Paper
      uses: actions/upload-artifact@v2
      with:
        name: Paper
        path: paper.pdf
        if-no-files-found: error

    - name: Check Spelling
      run: make check-spelling
