name: CI

on: [push, pull_request]


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt install pandoc texlive-latex-recommended texlive-latex-extra texlive-science

    - name: Render Paper
      run: pandoc -C --template=template.tex -o paper.pdf paper.md

    - name: Save Paper
      uses: actions/upload-artifact@v2
      with:
        name: Paper
        path: paper.pdf
        if-no-files-found: error
